### ISSUE TITLE
hold a 2015 summit

### ISSUE THREAD

**Issue by whit537** [opencompany/www.opencompany.org#142]
http://www.opencompany.org/summit/

What's the plan?

**Comment by tenkabuto** [comment]
@whit537 was kind enough to let me come for last year's summit, but I ended up not being able to go. In case you're willing to let me attend this year, would you all be opposed to it being held on a friday, saturday, or sunday?

**Comment by galuszkak** [comment]
@tenkabuto I agree. Weekend is actually better than other days of week for hosting event.

**Comment by whit537** [comment]
@kyledrake It seems from [The First Neocities Open Company Report](https://neocities.org/blog/open-company-progress-report-2014) that you're really digging OCI. That's awesome! :dancer: The fact is that Balanced and Gratipay are a little burned out on OCI at this point, so it's really encouraging to have some new energy in the group.

So, that said ... would you be willing to organize the 2015 OCI Summit? :-) The commitment would be to organize a fairly informal one-day event sometime this spring, with a budget of [about $2,400](https://gratipay.com/OpenCompany/members/). For comparison you can check out our past events here:

http://www.opencompany.org/summit/

Waddya say? Up for taking the baton? :-)

**Comment by kyledrake** [comment]
I'm definitely interested in continuing the summit. Preliminarily, I'm interested. Would Gratipay and the Balanced teams be attending if I did run one?

One of the things I'm interested in is trying to define a more specific idea of what an open company is. This probably is better done as a non-OCI but related project, and then OCI becomes a general platform for the concept so we can come together and flesh things out, so I like that.

Some basic blueprints would be nice. Where should it be located (probably SF), who I should invite, that kind of thing.

**Comment by whit537** [comment]
@kyledrake Fantastic, thank you!

I will make every effort to attend, yes. I'd like to propose that we use some of the budget to sponsor travel (I know that would help me a lot, at least).

@jkwade Is Balanced in?

> One of the things I'm interested in is trying to define a more specific idea of what an open company is. This probably is better done as a non-OCI but related project, and then OCI becomes a general platform for the concept so we can come together and ~~flesh things out~~ discuss what it means to be an open company in a general and nonspecific way, so I like that.

Related tickets: #41 #55 #129. I think we should focus on behaviors. Like, "here are a bunch of practical open-company-ish things you can implement at your company starting today." That's behind the pattern library idea (#129). I guess I'm going for more of a Wittgensteinian definition-in-use model than an essentialist ontology. ;-)

> Some basic blueprints would be nice. Where should it be located (probably SF), who I should invite, that kind of thing.

Last year we had about a dozen of us meet for crepes and conversation at Balanced HQ. The event was about three hours long. We've got about twice as many companies on board this year, so depending on interest I could see the summit being 15-20 people meeting for 3-5 hours this year? Audience is primarily leadership of current and prospective OCI members, but should be open to the public.

SF seems a safe bet in terms of attendee travel, though if we have more than a dozen people I think we're pushing the limits of comfort for Balanced's space. If you and @ericholscher want to make it happen in Portland that could work, too. @timothyfcook and I have to travel either way.

Let's kick out separate tickets in the repo here as needed and use a Summit 2015 milestone to keep track.

@timothyfcook Can we get Twitter creds to @kyledrake so he can start promoting there?

**Comment by ericholscher** [comment]
:+1: Happy to host it in PDX at the PIE space. We have a nice conf room that can easily hold 10-15 folks for a full day. Lodging is likely cheaper than in SF as well, but still quite easy to fly into.

**Comment by ericholscher** [comment]
PIE space can probably hold 20 -- it's a big room.

Would likely also be workable to have in the PDX Mozilla space if we pre-arrange, or some other friendly office space. Not sold on having it in PDX, but happy to oblige if people are interested.

**Comment by timothyfcook** [comment]
The mozilla space sounds cool and thematically relevant. I’ve been working with some folks over there lately. They would be a great addition to the OCI, could be a good reason to strike up a conversation with them about it if we’re meeting in their space.

Thoughts on a date?

**Comment by Frijol** [comment]
Commenting to make sure I get pinged with updates :)

I'm personally interested in attending, and could almost certainly offer our office space if it's on a weekend. We're in Berkeley, CA, pretty accessible by public transportation from SF. Office could hold up to 40 if pressed. (tessel.io, office pics here: https://foursquare.com/v/technical-machine/535ea931498edf967bcb436c/photos)

Is our space of interest?

**Comment by timothyfcook** [comment]
since we're an opencompany does that mean we can share our twitter creds publicly? 

login: opencompanyorg
password: secretcompany

**Comment by whit537** [comment]
> since we're an opencompany does that mean we can share our twitter creds publicly?
>
> login: opencompanyorg
> password: secretcompany

That was a really interesting decision! :scream: Thank you for helping us explore the limits of openness. :-)

I propose `*ahem*` that our Twitter password not be public, for the following reasons:

 - Anon could Tweet as us.
 - Anon could access our Gratipay account, and give all our money to themself.
 - Anon could change our Twitter password, and we wouldn't have either account (Twitter or Gratipay) anymore.

To avoid the above scenarios, I've gone ahead and changed the Twitter password. :-)

I'll email the new password to you, @galuszkak (who I believe had access before, yes?), and @kyledrake.

@frijol Want to help us run the Twitter account? :)

**Comment by timothyfcook** [comment]
haha. Thought you would like that! (also thought you would change it). I didn’t have folks e-mails and that seemed like the easiest route.

: - )

**Comment by whit537** [comment]
To be honest I would say that crossed the line into recklessness. :-(

Open companies have to be *really careful* about safety. I believe that open companies will turn out to be safer in the end than closed companies (for the same reasons why open-source software is more secure than closed-source software), but there's very little room for flippancy. Openness can be threatening. We are stewards and we have to take that seriously.

**Comment by timothyfcook** [comment]
Heard. Failing up.

**Comment by whit537** [comment]
!m @timothyfcook

**Comment by galuszkak** [comment]
Yes I had an access to Twitter. 

@timothyfcook sharing password isn't about being open ;) . Really. But apart from that, President of European Council when he was prime minister in Poland had his password on sticker on laptop http://niebezpiecznik.pl/post/haslo-premiera-donalda-tuska/. 
So this happens everywhere ;).

**Comment by kyledrake** [comment]
@timothyfcook I'm 100% no on open security. I think security is really important, and that these are valid secrets for an open company to maintain. If not you're just going to get torn apart by trolls right away.

I see the goal of an open company to be as open as possible about things like revenues, source code, governing policites, and operations. But for example, [Neocities](https://neocities.org) shares our source code for the site, but we do not share our secrets (which are stored in a config.yml file that is not checked into git). I also do not share the true location of our servers behind our proxies, both to prevent hackers/DDoS attacks against our core infrastructure, and also to give us a legal barricade, which is important to us since we're providing free hosting to the public internet.

Much to discuss here. Much. :)

Happy to host in PDX, we would be able to get an excellent venue.

@ericholscher is far more capable of doing this well than I am, he is an excellent planner with deep experience in this field with his work on things like Write the Docs, and I would be happy to collaborate on this with you Eric if you're interested. :)

Flights and accomodations are very affordable from SF to PDX, and I could scrounge up some couches and guest rooms for people on a budget, and could set up something fun to do after. So yeah, that could be great!

**Comment by whit537** [comment]
> Some basic blueprints would be nice.

Alright, @kyledrake, I went ahead and made a Summit 2015 milestone, and I stubbed out a bunch of tickets:

https://github.com/opencompany/www.opencompany.org/milestones/Summit%202015

I have a call with @jkwade this afternoon, to find out the extent to which Balanced wants to be involved. Along those lines, maybe #158 would be a good place to start?

**Comment by whit537** [comment]
Had a good call catching up with @jkwade. tl;dr is that Balanced is a maybe to attend the summit, and is ready to let someone else host it this year.

**Comment by galuszkak** [comment]
How is this going? Any progress on preparations? @kyledrake @whit537 @ericholscher

**Comment by tenkabuto** [comment]
Does the Summit need to be held at a participating company's location? We
may be able to reserve a conference room at a public library in SF, use the
internet there for live broadcast, and then go to lunch somewhere nearby.

**Comment by galuszkak** [comment]
@tenkabuto this should probably go to @kyledrake

**Comment by galuszkak** [comment]
@kyledrake knock, knock ? ;) On what page we are with summit?

**Comment by webmaven** [comment]
Does Balanced's shutdown affect anyone's decision to attend?

**Comment by tenkabuto** [comment]
@webmaven I'd still like to attend. Having one of the Balanced folks there
would be nice too, if only to tell them "good effort, guys."

**Comment by whit537** [comment]
Closing old tickets.
