### ISSUE TITLE
Leaving the project

### ISSUE THREAD

**Issue by kyzh** [opencompany/www.opencompany.org#145]
In the light of the views express by the leader of the OCI, I no longer wish to be part and or associated with OCI.

The views expressed in here are 
antagonistics with mine https://github.com/gratipay/inside.gratipay.com/issues/118 

Being a long debate, here the comments that I find offensive:
https://github.com/gratipay/inside.gratipay.com/issues/118#issuecomment-68358625
and
https://github.com/gratipay/inside.gratipay.com/issues/118#issuecomment-68370383

This is a public statement of dis-association with opencompany.

**Comment by whit537** [comment]
Best wishes, @kyzh.

**Comment by galuszkak** [comment]
@whit537 what we do with this https://gratipay.com/OpenCompany/members/  should kyzh be removed from OpenCompany members list?

**Comment by kyzh** [comment]
I have deleted my account (after hitting a bug)
The $ 0.37 received from being an OCI member on gittip/gratipay have been given to a charity.
