### ISSUE TITLE
Social media info about #ReadTheDocs #TechnicalMachine

### ISSUE THREAD

**Issue by galuszkak** [opencompany/www.opencompany.org#147]
Twitter/G+/Facebook.

**Comment by galuszkak** [comment]
https://twitter.com/OpenCompanyOrg/status/552413647889518592
https://www.facebook.com/OpenCompanyInitiative/posts/791299660940858
https://plus.google.com/b/104826670031041368281/+OpencompanyOrg/posts/cwdQQcMZwmR

Like, Share, RT, +1 etc.  
If it's all ok then close @whit537 :+1:

**Comment by whit537** [comment]
Thanks @galuszkak! :-)
