### ISSUE TITLE
fix logo on G+ page

### ISSUE THREAD

**Issue by whit537** [opencompany/www.opencompany.org#148]
What's up with this, @galuszkak?

![screen shot 2015-01-08 at 11 37 49 am](https://cloud.githubusercontent.com/assets/134455/5666057/dea8e752-972a-11e4-802e-597c529f50ac.png)

**Comment by waldyrious** [comment]
That's not a problem with the logo; it seems it's the cover image that's not adequate (the logo in G+ is shown cropped within a circle).

**Comment by galuszkak** [comment]
Yes @waldyrious is right. It depends what screen you have on bigger screens it looks more fine. Do we have some designer who could fix that? (or in background we set something different than logo, some photo from summit or pattern). What do you think @whit537 ?

**Comment by whit537** [comment]
Can we drop back to a pattern for now? Doesn't Google give us a bunch to choose from, iirc?

**Comment by galuszkak** [comment]
Fixed.

**Comment by waldyrious** [comment]
Link for future reference: https://plus.google.com/+OpencompanyOrg

**Comment by techtonik** [comment]
Why the page name is not capitalized? Post Capitalizing just Org seems ugly.

**Comment by galuszkak** [comment]
This was proposal from google and it couldn't be changed. I know it could
look ugly but at the time when I was creating it was like that.
But when you share link you can capitalize it and it will work
https://plus.google.com/+OpenCompanyOrg .

Thanks
Kamil

Why the page name is not capitalized? Post Capitalizing just Org seems ugly.

—
Reply to this email directly or view it on GitHub
<https://github.com/opencompany/www.opencompany.org/issues/148#issuecomment-78210986>
.
