### ISSUE TITLE
fix deployment pipeline

### ISSUE THREAD

**Issue by whit537** [opencompany/www.opencompany.org#149]
I believe our deployment pipeline is broken because we were depending on kyzh's credentials, and he's left the project (#145). We have commits in this repo without corresponding commits in our GitHub pages repo.

### Source

![screen shot 2015-01-08 at 12 03 46 pm](https://cloud.githubusercontent.com/assets/134455/5666559/6ee790b8-972e-11e4-8ea2-2195058f287c.png)

### Built

![screen shot 2015-01-08 at 12 03 31 pm](https://cloud.githubusercontent.com/assets/134455/5666554/63c9f9fa-972e-11e4-9a5d-316ab137c26b.png)

**Comment by galuszkak** [comment]
I will fix that.

**Comment by seanlinsley** [comment]
You should be able to add a deploy key to the repo itself, so the SSH key isn't tied to a specific user.

**Comment by whit537** [comment]
I started looking at this but ran out of time. Shelving tab state:

https://developer.github.com/guides/managing-deploy-keys/
https://help.github.com/articles/git-automation-with-oauth-tokens/
https://help.github.com/articles/creating-an-access-token-for-command-line-use/
https://help.github.com/articles/generating-ssh-keys/
https://github.com/opencompany/opencompany.github.io/settings/keys
https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db
https://github.com/opencompany/www.opencompany.org
https://github.com/opencompany/opencompany.github.io/commits/master
http://docs.travis-ci.com/user/deployment/custom/
http://docs.travis-ci.com/user/encrypting-files/
http://docs.travis-ci.com/user/deployment/custom/ :-)

**Comment by whit537** [comment]
I made a key and was looking at encrypting it to include in the repo and then figure out the changes needed to `after_success` to work with it instead of an OAuth token. OAuth tokens are tied to a user, we want a deploy process that's not dependent on a particular user so we're looking at a deploy key.

**Comment by galuszkak** [comment]
I get sick last week so sorry about delay @whit537 . I will try to fix that today...

**Comment by galuszkak** [comment]
This seems most resonable:
http://stackoverflow.com/a/23284673/161281

I will proceed with that. :)

**Comment by galuszkak** [comment]
ok I screw up this. I will regenerate second key, and try with encrypt-file.

**Comment by galuszkak** [comment]
I finally get it right, but ssh-add is asking for passphrase that doesn't exist it should automaticly add key... Someone have thoughts? @whit537 @seanlinsley

**Comment by galuszkak** [comment]
Could be this:

> IMPORTANT NOTE: When pasting the private key data in to the environment variable, you will need to double escape the newline characters. That means, not only will you need to convert the newlines to “\n”, but you’ll also need to escape the backslash. You’ll need to paste the newlines as “\\n”.

**Comment by galuszkak** [comment]
This works! Yay! Fixed ;)
