### ISSUE TITLE
plan for diversity/CoC

### ISSUE THREAD

**Issue by whit537** [opencompany/www.opencompany.org#156]

**Comment by galuszkak** [comment]
I'm entirely supporting especially CoC.

But what do we mean by diversity? How we measure this? By owners of companies that are members? Or somehow other way?
I'm not sure how do you think about that.

**Comment by tenkabuto** [comment]
What do you mean by a "CoC"? Certificate of Conformity?

**Comment by whit537** [comment]
Is that snark, @tenkabuto? Snark about diversity and codes of conduct aren't appropriate here.

**Comment by tenkabuto** [comment]
@whit537 I thought it seemed out of place. That's what I found when I googled [CoC](http://en.wikipedia.org/wiki/COC). I'm not clever enough to make such a joke. Thanks for clarifying. :sweat:

**Comment by whit537** [comment]
> That's what I found when I googled CoC. I'm not clever enough to make such a joke.

Phew. :-)

!m @tenkabuto

**Comment by whit537** [comment]
Closing old tickets.
