### ISSUE TITLE
clean up collaborators structure

### ISSUE THREAD

**Issue by whit537** [opencompany/www.opencompany.org#160]
This repo is basically our main means of communicating with each other, and so the way we organize collaborators has a big effect on who is getting notifications and therefore noticing what is going on with OCI. Right now we have the "Owners" team:

![screen shot 2015-01-21 at 10 09 42 am](https://cloud.githubusercontent.com/assets/134455/5838554/3d0b1560-a156-11e4-8d1b-d7dfda45ba1d.png)

I think we should trim up the owners team to just a few people with admin control. We should probably have a board that we elect at the Summit, and the board appoints people to the Owners team on GitHub.

Then I think we should have a larger Members team that has read/write access on www.opencompany.org. We should try to have at least one representative for each company on that team, our main contact person for that company.

**Comment by whit537** [comment]
I'll leave this open for comment for a while before diving in.

**Comment by whit537** [comment]
Of course, we're kind of chicken and egg here, aren't we, since no-one will have been notified in order to come over here and comment. :-/

**Comment by whit537** [comment]
Alright, I went ahead and made a `Company Reps` team and added/invited people for each of our current members:

![screen shot 2015-01-21 at 10 41 55 am](https://cloud.githubusercontent.com/assets/134455/5839142/3510d634-a15a-11e4-98d7-9b4b53c41c91.png)

**Comment by whit537** [comment]
Then I made a "Collaborators" team for individuals who are working with us, and I made the following changes to the "Owners" team:

 - removed @steveklabnik and @JustinSeaman07 (used to work for Balanced and Saxifrage, respectively)
 - moved @tenkabuto @Dispatches @vielmetti @ityonemo  to "Collaborators"

This leaves @timothyfcook @jkwade @galuszkak and myself on "Owners." Yes, this is by fiat. Sorry. As mentioned above we should organize a proper board that appoints GitHub Owners. Let's put that on the agenda for Summit 2015 (#154).

**Comment by whit537** [comment]
I guess that's that.

**Comment by whit537** [comment]
> Yes, this is by fiat. Sorry.

Of course, if you think I made a wrong decision about you during this reshuffle, please say so. :-)

**Comment by tenkabuto** [comment]
I should be removed as a Collaborator until I've had a more active role in OCI discussions. :confused:

**Comment by whit537** [comment]
Ping @ericholscher @kyledrake @ericmeltzer @dcramer @ipmb. You should have an invitation to join the "Company Reps" team for OCI. This ticket is context. :-)

**Comment by whit537** [comment]
Ping @balupton @dreeves @joelg @KimlingLam @josemarluedke @Frijol. You should have an invitation to join the "Company Reps" team for OCI. This ticket is context. :-)

**Comment by whit537** [comment]
> I should be removed as a Collaborator until I've had a more active role in OCI discussions. :confused:

@tenkabuto If you insist. You can probably do that yourself, no?

**Comment by tenkabuto** [comment]
@whit537 I didn't realize that I could. Done. :sweat:

**Comment by whit537** [comment]
:)

You're welcome back any time!

**Comment by balupton** [comment]
Joined with pride :)

**Comment by whit537** [comment]
@balupton Huzzah! :dancer:
