### ISSUE TITLE
Open Source Days talk about OCI

### ISSUE THREAD

**Issue by galuszkak** [opencompany/www.opencompany.org#163]
I've submitted talk about OCI in Open Source Days in Poland, Europe.

http://www.confeture.com/en/conferences/276-dni-wolnego-oprogramowania-15/talks/984-open-company-initiative

If someone could help with it I will greatly appreciate his/her time devoted to helping with that talk ;)

**Comment by whit537** [comment]
Nice! How long is the talk?

**Comment by galuszkak** [comment]
20 min. So plenty of time to talk about idea and examples ;) .

Thanks
Kamil

**Comment by whit537** [comment]
Have you written an outline for your talk yet?

**Comment by galuszkak** [comment]
I didn't get time for talk, but instead I was invited to discussion panel about "Building involvment in self organising teams".

Here is introduction:
http://mikstura.it/pl/blog//2015/04/14/dwo_2015_management_3_0_workout_somoorganizujace_zespoly.html

**Comment by galuszkak** [comment]
Closing as this happened already :).
