### ISSUE TITLE
re-launch as an independent initiative

### ISSUE THREAD

**Issue by whit537** [opencompany/www.opencompany.org#166]
Reticketed from #164:

> A third option, if you want to reduce the complexity/scope of the OCI, is converting the whole site/initiative to a simple (perhaps even single-page) website, which would essentially be a nicely-presented, html version of the awesome-open-company document (and still editable by anyone, through PRs).

+1. I think the time is right for OCI to become an independent initiative, separate from any particular open company. @waldyrious is the right person to lead it, because of his work on https://github.com/waldyrious/awesome-open-company.

Balanced and Saxifrage were the two co-founders of OCI along with Gratipay. Balanced is going out of business. Saxifrage is dormant (and, anyway, I talked this over with @timothyfcook at lunch today ;). No-one else seems to care or be paying much attention.

Here's what this entails:

 - [x] make @waldyrious an admin of this repo
 - [x] hand off DNS to @waldyrious
 - [x] hand off Twitter to @waldyrious

With Twitter access you'll be able to sign up for a Team on Gratipay, and thereby access the OCI balance there as well as start receiving recurring payments again.

I would like to no longer be an admin or manager of OCI. I believe @timothyfcook is interested in staying on with OCI in some capacity. Of course, I'm happy to participate as an "outsider" and especially to support and promote OCI from over at Gratipay. :-)

**Comment by whit537** [comment]
@waldyrious I've invited you to be an Owner of the opencompany org on GitHub. Once you accept the invitation I will remove myself from the org.

**Comment by whit537** [comment]
I've initiated an email change for the Twitter account. You should get a confirmation from them, @waldyrious. Based on your GitHub profile, I used waldyrious+oci@gmail.com.

**Comment by whit537** [comment]
@waldyrious Can you start a transfer request for the two domains?

`opencompany.org`
`opencompany.biz`

**Comment by whit537** [comment]
@timothyfcook is holding the domains currently so he will have to approve the transfer.

**Comment by tenkabuto** [comment]
I agree that the OCI should become separate from any particular open company, but I do not agree that it should be converted "to a simple (perhaps even single-page) website." The website current OCI should be restructured to integrate @waldyrious's work, as it's good work, but the OCI website should mostly articulate and make a strong argument for open companies --- problem is, we don't really know what an open company is, yet.

At least until there is a clearly articulated vision for what an open company is, I think that the OCI should be facilitating discussion about the concept and prospect of open companies.

**Comment by galuszkak** [comment]
@whit537 this should also include moving Facebook (50 likes) and G+ account to @waldyrious  I think.

IRC is dead. I'm only one who is on channel ##opencompany. Probably should be abandom or not?

**Comment by galuszkak** [comment]
@tenkabuto I think this goes to last discussion here: #134 .

**Comment by waldyrious** [comment]
As I said earlier, I'm glad to join the team behind the OCI, but I don't want stuff to depend entirely on me (bus factor, technical know-how transfer, time-zone responsiveness, etc.). If at least @timothyfcook stays around (and the rest of you remain involved even if as "outsiders"), I can take on most maintenance responsibilities (it might be useful to clarify exactly what these are just so we're all in the same page).

Now on to the practical stuff:
- [x] I've joined the OpenCompany org
- [x] I've transferred awesome-open-company to the org
- [ ] I got the email from Twitter, but I can't confirm the email address without the login details for the OpenCompanyOrg account; someone please email them to me (btw has anyone tried to contact the owner of the OpenCompany account, or Twitter regarding it?)
- [ ] I will request the transfer of the domains. I currently have domains registered in both Google Domains and Dreamhost. Do you have a preference on which registrar I should use for the OCI domains?
- [ ] I agree it may not make much sense to keep the IRC channel if nobody uses it. But maybe we could set up a Gitter chat room for the github org/repo, since it allows both synchronous and asynchronous communication (by keeping a log). Or we could use a google groups-based mailing list, which may be more appropriate (better archive/navigation) if there are no plans/expectations to have real-time discussions in the foreseeable future.

Let's settle the technical issues and then have a discussion about the direction / format this should take moving forward (e.g. what @tenkabuto says)

**Comment by galuszkak** [comment]
I will be involved but as I said before it will be limited time mostly because of other responsibilites (Hackerspace, my company S4F etc).

@waldyrious  I can take care of that Facebook page for now.
To gitter I think I talked about it with Chad couple of months back (or maybe it was slack? there is big hype now arround that tools ). For me both works and I don't have preference which is better for us. Actually mostly because lack of botbot.me or other logging bot IRC is unusable as other can't see conversation when they aren't around. Slack as far I know hold only 10k messages back. So gitter I think it's safer to choose for history/archive purposes. I think google group now it's just the same thing like conversation for GitHub so I'm not sure if we want that. For meetings/quick discussions Gitter should be fine. For longer we have this Github issues which I think are sufficient (there isn't too much people here so I suspect it's ok to keep for now most discussion on GitHub).

**Comment by waldyrious** [comment]
Fair points regarding discussion platforms. In that case I'd suggest keeping github issues and a gitter chat (I believe slack works in an invite model, while in gitter anyone with a github account can join).

**Comment by whit537** [comment]
> I can't confirm the email address without the login details for the OpenCompanyOrg account; someone please email them to me

Done.

**Comment by whit537** [comment]
@tenkabuto You've been around since the beginning and I think you've got good ideas and energy. As my last act on the Owners team of this GitHub org, I've invited you to join @timothyfcook, @galuszkak  and @waldyrious as an owner. :-)

Well, I guess technically my *last* act was to remove myself. :-P

I've also removed myself from the Facebook page (@galuszkak and @timothyfcook are admins there), and it doesn't look like I have access to Google+ anyway, so we're good there.

I've also removed myself from the @opencompany/company-reps team, and it probably makes sense to dissolve that team as part of this ticket.

Good luck, @waldyrious @galuszkak @timothyfcook @tenkabuto! May you facilitate much discussion about the concept and prospect of open companies! :dancer: :dancers:

**Comment by waldyrious** [comment]
Ok, Twitter setup is done. Who can comment in the remaining checklist items (domains, G+, chat room)?

@whit537 I hope you will remain around; your insights and drive were crucial in the formation of the OCI and still are for its future :)

**Comment by galuszkak** [comment]
@waldyrious I give you access on G+ page.

**Comment by whit537** [comment]
Thanks @waldyrious. :-)

P.S. I think it'll actually work best if I *don't* watch the org/repo, because then I'll actually notice when you @mention me when my input will be most valuable. I've learned from experience on other repos that if I receive all notifications, I tune them out even if you @mention me. :-)

**Comment by waldyrious** [comment]
@galuszkak thanks, I just accepted the invitation and checked off the box above :+1:.

Let me know how to proceed regarding the domains. (By the way, if you guys prefer that someone else manages them instead, so we don't put all eggs in one basket, that's fine with me also. The only reason I'm accepting all these responsibilities is because I don't want the initiative to die off by lack of volunteers to keep it going.)

**Comment by tenkabuto** [comment]
I did not expect to be made an Owner, but alrighty then. :grin: I'm barely familiar with using GitHub and GitHub's Issues, so I'll try to contribute without messing things up. :dancer: 

In the Gitter FAQ, Gitter mentions that [authorizing the app with GitHub gives Gitter write access to your private repos](https://gitter.zendesk.com/hc/en-us/articles/200178971-You-want-write-access-on-my-private-repos-Are-you-insane-), so we might not want to use it.

Lastly, I haven't been receiving @mention notifications, but I'll check my notifications and email often.

**Comment by tenkabuto** [comment]
I misunderstood the Gitter FAQ article. :sweat: Apparently [Gitter asks for authorization for access to your open repos and can also do so for private repos](https://gitter.zendesk.com/hc/en-us/articles/200176672-Authenticating-with-GitHub), but it does not do both at the same time, so we should be able to use Gitter.

**Comment by waldyrious** [comment]
Great to hear that. I really like gitter model. It fills a pretty sweet spot between asynchronous communication and real-time chat.

**Comment by waldyrious** [comment]
@tenkabuto has set up a gitter chat room [here](https://gitter.im/opencompany). We're currently not sure whether anyone can join. @whit537 I think you're in the perfect position to help us figure that out :D

**Comment by whit537** [comment]
Shows up as "locked":

![screen shot 2015-09-07 at 9 23 36 pm](https://cloud.githubusercontent.com/assets/134455/9724505/bd5434ea-55a6-11e5-8a8b-84fdc9710172.png)

**Comment by tenkabuto** [comment]
Thanks, @whit537. I figured out that though the main chat room for the OCI org is for org members only, we can make additional rooms per repo or as a channel that can be public. I made this general one that anyone can join: https://gitter.im/opencompany/general To stay open, we may want to operate primarily in the additional rooms.

**Comment by waldyrious** [comment]
> To stay open, we may want to operate primarily in the additional rooms.

Agreed. I don't see why we'd need more than one room, though, and tbh "general" doesn't sound like a good chat room name (it would if there were to be other rooms). Maybe name it "OCI" or "chat", something like that?

**Comment by tenkabuto** [comment]
Sure. We can delete the "general" room and create others. :)

**Comment by waldyrious** [comment]
@tenkabuto do you like any of the names I suggested? Would you prefer something else?

**Comment by tenkabuto** [comment]
@waldyrious "chat" is fine.

**Comment by galuszkak** [comment]
@waldyrious  I think we have here some not fixed tasks above. Does domain were transfered to you by @whit537  ? (in whois there is info that Chad still poses domains).

**Comment by waldyrious** [comment]
Nope, still waiting for feedback on that regard (even if it is in the form of "let's keep the domain(s) as is for now"). Some resolution is needed, indeed.

Quoting from @whit537 above, for context:

>  I believe @timothyfcook is interested in staying on with OCI in some capacity.
> (...)
> @timothyfcook is holding the domains currently so he will have to approve the transfer.

**Comment by galuszkak** [comment]
A right, I lost that one. I suggested with task by @whit537 :
"hand off DNS to @waldyrious"

:+1:

**Comment by galuszkak** [comment]
@waldyrious  btw what with OCI ballance on Gratipay. Did someone take care about that? AFAIR what whit537 was saying, there was 2000$ I think so it's a lot of cash that could be used for some good things

**Comment by waldyrious** [comment]
AFAIK nothing was done about that. In our next meeting we should probably discuss what needs to be done and how (or whether) to put the money to good use.

Btw, regarding the domains, I will also add a relevant quote (by myself) from above:

> I will request the transfer of the domains. I currently have domains registered in both Google Domains and Dreamhost. Do you have a preference on which registrar I should use for the OCI domains?

**Comment by galuszkak** [comment]
@waldyrious maybe you should email @whit537 he could probably miss notifications from GitHub.

**Comment by waldyrious** [comment]
He specifically said he'd turn off notifications from this repo so that pings would get his attention, so I'd wait a little more before reaching out elsewhere.

**Comment by whit537** [comment]
Thanks for pinging me, I'm listening. :-)

I'm working with @timothyfcook regularly (on https://github.com/saxifrage/cityasacampus), so I can bug him about things, too. I'm pretty sure @timothyfcook controls the domains. Now that you all have Twitter you should be able to access the funds on Gratipay (you can now [withdraw the balance indefinitely](https://medium.com/gratipay-blog/1-0-money-available-indefinitely-39c07bd031b)). What do you need from me/us?

Happy to see you all keeping the dream alive! :-)

**Comment by timothyfcook** [comment]
Ready to help with domain ownership transfer. I think you you need request it first.

**Comment by waldyrious** [comment]
@timothyfcook great :) I am kinda swamped these days so I'll take care of it on the weekend.

**Comment by waldyrious** [comment]
@whit537 @timothyfcook I've started the domain transfer process. Please send me the authorization code once you get the request.

**Comment by timothyfcook** [comment]
I didn't get any request... : (

**Comment by waldyrious** [comment]
@timothyfcook these are the instructions I got:

![screenshot](https://cloud.githubusercontent.com/assets/478237/11038640/f37c1dfe-86fb-11e5-98d3-93932705ba57.png)

Looks like you don't get a notification of the request? Or perhaps it went to @whit537. Maybe try logging in to the registrar's dashboard and see if you can get the transfer code.

**Comment by waldyrious** [comment]
Ah, it apears I need the code in order to even start the process.

**Comment by whit537** [comment]
I see my email address in your screenshot, @waldyrious. Looking into this ...

**Comment by whit537** [comment]
@waldyrious I've emailed you the authorization code. Let me know if you need anything else from me! :-)

**Comment by waldyrious** [comment]
Great, thanks :) I've initiated the transfer. This time I was told explicitly that they sent further instructions to your email, so take a look at that when you can.

**Comment by whit537** [comment]
I think I did it right? :)

![screen shot 2015-11-09 at 9 40 41 pm](https://cloud.githubusercontent.com/assets/134455/11052905/9a2d04a0-872a-11e5-90f0-bb039058d8f2.png)

**Comment by waldyrious** [comment]
Looks like it :)

> We have asked your current registrar to release opencompany.org to us. The transfer of your domain will complete immediately after your registrar releases it to us. However, your registrar may take up to five days (November 16, 2015) to process your transfer request. Please note, for security reasons your registrar may contact you directly and ask you to approve the transfer again.

**Comment by waldyrious** [comment]
Okay, all the items are checked, so I'll close this issue. (Hurray! :tada:)

Next steps will be tracked in #168.
