### ISSUE TITLE
Monthly meetings

### ISSUE THREAD

**Issue by galuszkak** [opencompany/www.opencompany.org#167]
Hi all,
I was thinking that some things are taking a little slow down and it will be great to move forward, so my proposal is to do monthly meetings (Gitter or Hangouts) to talk about what could be done, how can we move forward, and clean up issues in repository, take some tasks that we could help on. 

What do you think about that? @waldyrious @tenkabuto @timothyfcook 

Thanks :)

**Comment by waldyrious** [comment]
Fully agreed on my side. I admit I haven't insisted on pending tasks that depend on others, initially not to be too pushy, but we shouldn't get accommodated into a limbo state.

**Comment by tenkabuto** [comment]
That would be great! I've been a bit worried that @timothyfcook might have passed away or something, as he hasn't responded to the previously-raised Issues from over a month ago.

**Comment by galuszkak** [comment]
I'm not sure as I'm not native english speaker but what do you mean by passed away? It's probably lack of his free time. He maybe is busy with other things.

**Comment by tenkabuto** [comment]
I meant that he might have died or something, but his social profiles suggest otherwise. :sweat_smile:

**Comment by galuszkak** [comment]
OK so I propose to set a date of meeting. Here I'm not sure on which timezones you are guys. My is CET (UTC +1). Here is doodle it should help us find best time for us. I propose next week.
http://doodle.com/poll/gpkymdrxrh62qtqy#table

**Comment by timothyfcook** [comment]
Not dying. Just lots of good work opportunities and prepping to have my first child here soon!

Probably don't have time for monthly meetings, but happy to contribute to one-time happenings. I'll keep lurking!

**Comment by galuszkak** [comment]
@tenkabuto @waldyrious @timothyfcook reminder about checking on doodle what time works for You guys so we should now when to do this meeting.  http://doodle.com/poll/gpkymdrxrh62qtqy#table

**Comment by tenkabuto** [comment]
Thanks for the reminder, @galuszkak. I added my available time slots. :+1:

**Comment by waldyrious** [comment]
Uh, it looks like there's an incompatibility already: I can join most days of the week, but only at night. I see that @tenkabuto can't join precisely in the only time slot that was available for me (9pm WET, the last entry on each day). Would that change if we moved it one hour earlier? It would be a bit tight for me, but I could do it.

**Comment by tenkabuto** [comment]
I have a class 30 minutes into the time slot that @waldyrious is available, so I could join then for about 20 minutes. Moving the time slots forward might work. Are any of you guys available on Friday, which was excluded from the Doodle?

**Comment by galuszkak** [comment]
I've added friday and some additional hours. Can you update @waldyrious @tenkabuto . Sorry about mess :)

**Comment by tenkabuto** [comment]
Thanks for updating the poll. I've updated my time slots. Since I voted
before I've become available on Tuesday 11/10/15 (tomorrow), in case you
guys would like to do it then.

Would you guys like to put together an agenda of things that we might want
to discuss?

**Comment by waldyrious** [comment]
I've updated my slots as well. As for an agenda, I will propose something tonight (unless tonight is the day that ends up chosen :P)

**Comment by waldyrious** [comment]
I've started a draft document with some topics to address [here](https://docs.google.com/document/d/16V1Y5zQY1RsIw37YKEghNcKcQaVgQAI2WZiLhGeQ6q4/edit).

Btw @galuszkak are you going to close the doodle poll? Are you waiting for @timothyfcook?

**Comment by galuszkak** [comment]
@waldyrious yes sorry so long. I see most time we have in Friday. Could be it? Or tommorow is better?

**Comment by waldyrious** [comment]
Friday looks like a better pick, yeah.

**Comment by galuszkak** [comment]
OK. Then let it be Friday. I closed pool. Please mark your calendars :+1: 

This draft BTW looks awesome ;) I will contribute in free time.

**Comment by tenkabuto** [comment]
Here's a link to the Google Hangouts room that I started: https://hangouts.google.com/call/xqrha7gv43dws4ys3yub2x4c2ma

**Comment by tenkabuto** [comment]
No one joined the room during the hour. Hopefully we can re-schedule for next week or something.

**Comment by waldyrious** [comment]
I'm sorry, guys. I spent most of yesterday and today chasing down a pretty hairy bug and only managed to get home about an hour ago. How do you feel about scheduling the call for sometime during the weekend?

**Comment by tenkabuto** [comment]
I'm available nearly all day during the weekend. Maybe we should reopen the
poll, though? :sweat: Would you guys be willing to meet for a two hour
period to have a more relaxed chat?

**Comment by galuszkak** [comment]
Gosh sorry, I also went longer in work and my calendar didn't remind it to me. I'm open for all weekend. Tommorow same hours is ok?

**Comment by waldyrious** [comment]
For me it can be all day except tonight (saturday), so that option's not workable. @tenkabuto are you on PST? If so, that gives us a [relatively narrow interval](http://www.worldtimebuddy.com/utc-to-pst-converter) to pick from, but it's quite doable. Let's do it tomorrow (sunday) at the same time (8pm UTC) so we all have time to confirm.

**Comment by galuszkak** [comment]
@waldyrious works for me.

**Comment by tenkabuto** [comment]
@waldyrious Works for me, too. (We established this via a Hangouts chat, but I'm posting it here for the record.) I should be able to use a laptop with a webcam tomorrow, too! :smile:

**Comment by galuszkak** [comment]
Video archive from yesterday call: https://www.youtube.com/watch?v=eYJPx9DQIVw

**Comment by waldyrious** [comment]
I wasn't able to make the summary of the meeting today as promised, other stuff piled up. I'll try to do it tomorrow.

**Comment by waldyrious** [comment]
Ok, I've started #168 to track the decisions and actions agreed in the past meeting, and since a schedule for the meetings has been decided, I'll close this issue as resolved.
