### ISSUE TITLE
December 2015 Meeting

### ISSUE THREAD

**Issue by tenkabuto** [opencompany/www.opencompany.org#169]
Let's plan here what we will have the December 2015 meeting and what we will discuss during the meeting.

- [ ] When's the meeting:
- [ ] What we will be discussing:
    - Points not addressed in #168, the issue for the last meeting 
    - ...

**Comment by tenkabuto** [comment]
Last meeting (#168) we came up with the schedule of every second Sunday of each month, which would have us meet this month on Dec. 13th.

Unfortunately, my final exams are the week following the 13th, so I will be studying and unable to prepare for our meeting if it is on the 13th. Also, I will likely be busy with church around 8pm UTC on Sunday the 20th, as it is the Sunday before Christmas. Accordingly, could we please postpone this month's meeting to that Saturday, the 19th?

**Comment by waldyrious** [comment]
I don't think I can make it this month, guys. My workload has increased exponentially as well as social commitments, both of which eat up my free time. I didn't even have the chance to properly finish processing the log for the last meeting. I'd say let's skip the December meeting and meet January 10th per the agreed schedule. Thoughts?

**Comment by tenkabuto** [comment]
We did not meet in either Dec '15 or Jan '16, but we did in Feb 2016; see #170 for notes about and logs of that meeting.
