### ISSUE TITLE
Travis CI deploy doesn't work

### ISSUE THREAD

**Issue by galuszkak** [opencompany/www.opencompany.org#173]
I think I know why Travis is failing.

I remember that this was setup by @kyzh or @whit537 . But that doesn't matter right now ;). What matters is that probably when they self removed from organisation their keys become invalid and that is why new build are erroring out because push to repository is the only step with error on travis.

So what I propose I will generate new key and add it to travis and repository so deploys can be done again.

What do think @waldyrious ?

**Comment by waldyrious** [comment]
That sounds like it could work. Do you know how to do it?

**Comment by galuszkak** [comment]
@waldyrious I fixed it today. After 4 years. Shame on me.
